"""Pure-Python chess game/logic library for the robot arm.  NO ROS imports.

This module is intentionally free of any ROS 2 dependency so the whole
move-resolution / move-decomposition logic is importable and unit-testable as
an ordinary Python library.  ``brain_node.py`` is the thin rclpy wrapper that
adapts these classes to the canonical ``chess_arm_interfaces`` services.

Key design rules (from the project spec):

* The engine / ``chess.Board`` is the **authoritative** game state.
* Vision only ever reports the *set of changed squares*; a human move is
  resolved by finding the unique legal move whose "touched square" set equals
  the observed changed-square set.  Piece type is never classified by vision.
* A move is decomposed into a sequence of robot *piece actions* computed on the
  board state **before** the move is pushed (the captured piece, rook squares,
  en-passant pawn square, etc. all depend on the pre-move position).

The action-type integer constants below mirror, value-for-value, the
``PieceAction.msg`` constants in ``chess_arm_interfaces`` so the node layer can
use them without translation.
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional, Sequence, Tuple

import chess
import yaml

# ---------------------------------------------------------------------------
# Action-type constants (must match chess_arm_interfaces/msg/PieceAction.msg).
# ---------------------------------------------------------------------------
ACTION_PICK_PLACE = 0
ACTION_CLEAR_CAPTURE = 1
ACTION_MOVE_ROOK = 2
ACTION_CLEAR_EN_PASSANT = 3
ACTION_REMOVE_PROMOTED_PAWN = 4
ACTION_PLACE_PROMOTION = 5

ACTION_NAMES: Dict[int, str] = {
    ACTION_PICK_PLACE: "PICK_PLACE",
    ACTION_CLEAR_CAPTURE: "CLEAR_CAPTURE",
    ACTION_MOVE_ROOK: "MOVE_ROOK",
    ACTION_CLEAR_EN_PASSANT: "CLEAR_EN_PASSANT",
    ACTION_REMOVE_PROMOTED_PAWN: "REMOVE_PROMOTED_PAWN",
    ACTION_PLACE_PROMOTION: "PLACE_PROMOTION",
}

# The graveyard slot reserved as the *source* for a spare queen used when a
# pawn promotes.  Allocator hands out slots from the opposite end so it never
# collides with this reserved source (see GraveyardAllocator).
PROMOTION_QUEEN_SOURCE = "GY16"


# ---------------------------------------------------------------------------
# Coordinates helper.
# ---------------------------------------------------------------------------
class BoardCoordinates:
    """Loads ``board_coordinates.yaml`` and resolves square / graveyard -> (x, y).

    The YAML (generated by ``chess_arm_description``) has the shape::

        units: m
        surface_z: 0.0
        grasp_z:   0.03
        lift_z:    0.11
        squares:   { a1: {x, y}, ..., h8: {x, y} }
        graveyard: { GY1: {x, y}, ..., GY16: {x, y} }

    Board centre is the world origin, the surface is at ``surface_z``; files
    run along +X and ranks along +Y.
    """

    DEFAULT_SURFACE_Z = 0.0
    DEFAULT_GRASP_Z = 0.030
    DEFAULT_LIFT_Z = 0.110

    def __init__(self, yaml_path: str):
        self.yaml_path = yaml_path
        with open(yaml_path, "r") as fh:
            data = yaml.safe_load(fh) or {}

        squares = data.get("squares", {}) or {}
        graveyard = data.get("graveyard", {}) or {}

        # Flat name -> (x, y) lookup covering both squares and graveyard slots.
        self._xy: Dict[str, Tuple[float, float]] = {}
        for name, pt in squares.items():
            self._xy[name] = (float(pt["x"]), float(pt["y"]))
        for name, pt in graveyard.items():
            self._xy[name] = (float(pt["x"]), float(pt["y"]))

        self.surface_z = float(data.get("surface_z", self.DEFAULT_SURFACE_Z))
        self.grasp_z = float(data.get("grasp_z", self.DEFAULT_GRASP_Z))
        self.lift_z = float(data.get("lift_z", self.DEFAULT_LIFT_Z))

        # Graveyard slot names in numeric order (GY1, GY2, ... GY16).
        self.graveyard_slots: List[str] = sorted(
            graveyard.keys(), key=lambda s: int(s[2:]) if s[2:].isdigit() else 0
        )

    # -- lookups ------------------------------------------------------------
    def has(self, name: str) -> bool:
        return name in self._xy

    def xy(self, name: str) -> Tuple[float, float]:
        """Return the (x, y) for a square ('e4') or graveyard slot ('GY3')."""
        try:
            return self._xy[name]
        except KeyError as exc:  # pragma: no cover - defensive
            raise KeyError(f"unknown board location '{name}'") from exc

    def xyz(self, name: str, z: Optional[float] = None) -> Tuple[float, float, float]:
        """Return (x, y, z); z defaults to grasp height."""
        x, y = self.xy(name)
        return (x, y, self.grasp_z if z is None else z)

    @classmethod
    def from_package_share(cls) -> "BoardCoordinates":
        """Locate the YAML inside the installed chess_arm_description share dir.

        Imported lazily so this module has no hard ament dependency when used
        purely as a library / in unit tests.
        """
        from ament_index_python.packages import get_package_share_directory

        share = get_package_share_directory("chess_arm_description")
        path = os.path.join(share, "config", "board_coordinates.yaml")
        return cls(path)


class GraveyardAllocator:
    """Hands out free graveyard slots GY1..GYn for cleared pieces.

    The reserved promotion-queen *source* slot is excluded from allocation so a
    cleared piece never lands on top of the spare queen we expect to fetch.
    """

    def __init__(
        self,
        slots: Sequence[str],
        reserved_source: str = PROMOTION_QUEEN_SOURCE,
    ):
        # Preserve numeric order; drop the reserved promotion-queen source.
        self._free: List[str] = [s for s in slots if s != reserved_source]
        self.reserved_source = reserved_source

    def next_slot(self) -> str:
        if not self._free:
            raise RuntimeError("graveyard is full: no free slot to clear a piece")
        return self._free.pop(0)

    def reset(self, slots: Sequence[str]) -> None:
        self._free = [s for s in slots if s != self.reserved_source]


# ---------------------------------------------------------------------------
# Stockfish wrapper (lazily opened so logic tests run without the binary).
# ---------------------------------------------------------------------------
class StockfishEngine:
    """Thin wrapper around ``chess.engine.SimpleEngine.popen_uci('stockfish')``.

    The engine subprocess is opened lazily on the first :meth:`best_move` (or
    explicit :meth:`open`) call, so importing/constructing this class — and
    therefore the whole logic library — never requires Stockfish to be present.
    """

    def __init__(
        self,
        command: str = "stockfish",
        skill_level: Optional[int] = None,
        elo: Optional[int] = None,
        movetime_ms: int = 1000,
    ):
        self.command = command
        self.skill_level = skill_level
        self.elo = elo
        self.movetime_ms = movetime_ms
        self._engine = None  # type: ignore[assignment]

    # -- lifecycle ----------------------------------------------------------
    def open(self):
        """Open (if needed) and configure the Stockfish subprocess."""
        if self._engine is not None:
            return self._engine
        import chess.engine  # imported lazily

        self._engine = chess.engine.SimpleEngine.popen_uci(self.command)
        self._apply_strength()
        return self._engine

    def _apply_strength(self) -> None:
        import chess.engine  # noqa: F401  (ensure module present for types)

        opts: Dict[str, object] = {}
        if self.elo is not None:
            opts["UCI_LimitStrength"] = True
            opts["UCI_Elo"] = int(self.elo)
        elif self.skill_level is not None:
            opts["Skill Level"] = int(self.skill_level)
        if opts:
            try:
                self._engine.configure(opts)
            except Exception:  # pragma: no cover - engine-specific option names
                # Be tolerant: not every build exposes every option.
                pass

    def configure(
        self,
        skill_level: Optional[int] = None,
        elo: Optional[int] = None,
        movetime_ms: Optional[int] = None,
    ) -> None:
        """Update strength / movetime; applied immediately if engine is open."""
        if skill_level is not None:
            self.skill_level = skill_level
            self.elo = None
        if elo is not None:
            self.elo = elo
            self.skill_level = None
        if movetime_ms is not None:
            self.movetime_ms = movetime_ms
        if self._engine is not None:
            self._apply_strength()

    @property
    def is_open(self) -> bool:
        return self._engine is not None

    def best_move(self, board: "chess.Board") -> "chess.Move":
        """Return Stockfish's best move for ``board`` (opens engine lazily)."""
        import chess.engine

        engine = self.open()
        limit = chess.engine.Limit(time=self.movetime_ms / 1000.0)
        result = engine.play(board, limit)
        if result.move is None:  # pragma: no cover - only at game end
            raise RuntimeError("engine returned no move")
        return result.move

    def close(self) -> None:
        if self._engine is not None:
            try:
                self._engine.quit()
            finally:
                self._engine = None

    def __del__(self):  # pragma: no cover - best-effort cleanup
        try:
            self.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# The brain: authoritative board + move resolution + decomposition.
# ---------------------------------------------------------------------------
class ChessBrain:
    """Holds the authoritative ``chess.Board`` and the game logic.

    Responsibilities:

    * :meth:`resolve_human_move` — turn an observed *changed-square set* into
      the unique legal ``chess.Move`` it corresponds to.
    * :meth:`push` — advance the authoritative game state.
    * :meth:`engine_move` — ask the lazily-opened Stockfish for a reply.
    * :meth:`decompose` — turn a move into the ordered list of robot piece
      actions, computed on the board state *before* the move is pushed.
    """

    def __init__(
        self,
        coordinates: Optional[BoardCoordinates] = None,
        engine: Optional[StockfishEngine] = None,
        board: Optional["chess.Board"] = None,
    ):
        self.board = board if board is not None else chess.Board()
        self.coords = coordinates
        self.engine = engine if engine is not None else StockfishEngine()
        slots = self.coords.graveyard_slots if self.coords is not None else []
        self.graveyard = GraveyardAllocator(slots)

    # -- game state helpers -------------------------------------------------
    def reset(self, fen: Optional[str] = None) -> None:
        self.board = chess.Board(fen) if fen else chess.Board()
        slots = self.coords.graveyard_slots if self.coords is not None else []
        self.graveyard.reset(slots)

    @property
    def fen(self) -> str:
        return self.board.fen()

    def push(self, move: "chess.Move") -> None:
        """Advance the authoritative game state by one (legal) move."""
        if move not in self.board.legal_moves:
            raise ValueError(f"illegal move {move.uci()} in position {self.board.fen()}")
        self.board.push(move)

    def is_game_over(self) -> bool:
        return self.board.is_game_over()

    def result(self) -> str:
        return self.board.result()

    # -- engine -------------------------------------------------------------
    def engine_move(self) -> "chess.Move":
        """Best move for the current position from the lazily-opened engine."""
        return self.engine.best_move(self.board)

    # -- move resolution from vision ---------------------------------------
    @staticmethod
    def _touched_squares(board: "chess.Board", move: "chess.Move") -> set:
        """Return the set of square names a move physically changes.

        * normal/quiet & capture: {from, to}  (capture still touches 2 squares
          on a 2D occupancy diff because vision can't see the colour change as
          "3 squares"; the destination's occupancy may not change, but its
          *content* does — we therefore include from+to for quiet/capture).
        * castling: {king_from, king_to, rook_from, rook_to}  (4 squares)
        * en passant: {from, to, captured_pawn_sq}  (3 squares)

    Note on captures: on a binary occupancy diff a normal capture only flips
    the *source* square (destination stays occupied).  To make the matching
    robust regardless of whether vision reports occupancy or content change,
    we treat the canonical touched set for quiet & capture moves as {from,to}
    and additionally accept the source-only set for captures (see
    :meth:`resolve_human_move`).
        """
        frm = chess.square_name(move.from_square)
        to = chess.square_name(move.to_square)
        touched = {frm, to}

        if board.is_castling(move):
            rook_from, rook_to = ChessBrain._rook_squares_for_castle(move)
            touched.update({rook_from, rook_to})
        elif board.is_en_passant(move):
            touched.add(ChessBrain._en_passant_captured_square(move))
        return touched

    @staticmethod
    def _rook_squares_for_castle(move: "chess.Move") -> Tuple[str, str]:
        """Derive (rook_from, rook_to) from the king's from/to of a castle."""
        king_from = move.from_square
        king_to = move.to_square
        rank = chess.square_rank(king_from)
        if chess.square_file(king_to) > chess.square_file(king_from):
            # King-side (h-side): rook h-file -> f-file.
            rook_from = chess.square(7, rank)  # h
            rook_to = chess.square(5, rank)  # f
        else:
            # Queen-side (a-side): rook a-file -> d-file.
            rook_from = chess.square(0, rank)  # a
            rook_to = chess.square(3, rank)  # d
        return chess.square_name(rook_from), chess.square_name(rook_to)

    @staticmethod
    def _en_passant_captured_square(move: "chess.Move") -> str:
        """Square of the pawn captured en passant (behind the destination).

        The captured pawn sits on the destination file, on the rank the moving
        pawn started from (i.e. to_square shifted back one rank toward the
        mover's origin).
        """
        to_file = chess.square_file(move.to_square)
        from_rank = chess.square_rank(move.from_square)
        captured = chess.square(to_file, from_rank)
        return chess.square_name(captured)

    def resolve_human_move(self, changed_squares: Sequence[str]) -> Optional["chess.Move"]:
        """Match an observed changed-square set to the unique legal move.

        ``changed_squares`` is the set of square names (e.g. ``['e2', 'e4']``)
        that vision reports as having changed since the last turn.  We compare
        it against the touched-square set of every legal move and return the
        unique match.

        Returns ``None`` when the observation is ambiguous (matches more than
        one legal move) or illegal (matches none).
        """
        observed = {s.lower() for s in changed_squares}
        matches: List["chess.Move"] = []
        for move in self.board.legal_moves:
            canonical = self._touched_squares(self.board, move)
            if observed == canonical:
                matches.append(move)
                continue
            # Tolerance for captures reported as a single (source) square flip
            # on a binary occupancy diff: {from} only, or {from, to}.
            if self.board.is_capture(move) and not self.board.is_en_passant(move):
                frm = chess.square_name(move.from_square)
                if observed == {frm}:
                    matches.append(move)

        if len(matches) == 1:
            return matches[0]
        return None

    # -- move -> piece-action decomposition --------------------------------
    def decompose(self, move: "chess.Move") -> List[dict]:
        """Decompose ``move`` into ordered robot piece actions.

        IMPORTANT: this must be called on the board state *before* ``move`` is
        pushed, because the captured piece, rook squares and en-passant pawn
        square all depend on the pre-move position.

        Each returned action is a dict::

            {
              'action_type': <int>,      # ACTION_* constant
              'from_square': <str>,      # square or 'GYn'
              'to_square':   <str>,      # square or 'GYn'
              'piece':       <str>,      # e.g. 'Q' for a promotion, else ''
            }

        World coordinates are *not* filled here (kept pure); the node layer
        looks up xyz via :class:`BoardCoordinates`.
        """
        board = self.board
        if move not in board.legal_moves:
            raise ValueError(
                f"cannot decompose illegal move {move.uci()} in {board.fen()}"
            )

        frm = chess.square_name(move.from_square)
        to = chess.square_name(move.to_square)
        actions: List[dict] = []

        is_castle = board.is_castling(move)
        is_ep = board.is_en_passant(move)
        is_capture = board.is_capture(move)
        is_promo = move.promotion is not None

        # --- castling: king first, then rook --------------------------------
        if is_castle:
            rook_from, rook_to = self._rook_squares_for_castle(move)
            actions.append(self._mk(ACTION_PICK_PLACE, frm, to))
            actions.append(self._mk(ACTION_MOVE_ROOK, rook_from, rook_to))
            return actions

        # --- pre-move clears (capture / en passant) -------------------------
        if is_ep:
            captured_sq = self._en_passant_captured_square(move)
            gy = self.graveyard.next_slot()
            actions.append(self._mk(ACTION_CLEAR_EN_PASSANT, captured_sq, gy))
        elif is_capture:
            gy = self.graveyard.next_slot()
            actions.append(self._mk(ACTION_CLEAR_CAPTURE, to, gy))

        # --- promotion ------------------------------------------------------
        if is_promo:
            promo_symbol = chess.piece_symbol(move.promotion).upper()  # 'Q' default
            gy_pawn = self.graveyard.next_slot()
            # Remove the promoting pawn from its origin to the graveyard, then
            # fetch the promoted piece from the reserved queen source slot.
            actions.append(self._mk(ACTION_REMOVE_PROMOTED_PAWN, frm, gy_pawn))
            actions.append(
                self._mk(
                    ACTION_PLACE_PROMOTION,
                    self.graveyard.reserved_source,
                    to,
                    piece=promo_symbol,
                )
            )
            return actions

        # --- plain move (quiet or after a capture clear) --------------------
        actions.append(self._mk(ACTION_PICK_PLACE, frm, to))
        return actions

    @staticmethod
    def _mk(action_type: int, from_square: str, to_square: str, piece: str = "") -> dict:
        return {
            "action_type": action_type,
            "from_square": from_square,
            "to_square": to_square,
            "piece": piece,
        }

    # -- coordinate enrichment (used by the node) --------------------------
    def with_coordinates(
        self,
        actions: Sequence[dict],
        pick_z: Optional[float] = None,
        place_z: Optional[float] = None,
    ) -> List[dict]:
        """Annotate actions with from_xyz / to_xyz using the coords helper.

        Requires that this brain was constructed with a ``BoardCoordinates``.
        ``from`` is at grasp (pick) height, ``to`` is at grasp (place) height;
        both default to ``coords.grasp_z``.
        """
        if self.coords is None:
            raise RuntimeError("no BoardCoordinates available for xyz lookup")
        pz = self.coords.grasp_z if pick_z is None else pick_z
        qz = self.coords.grasp_z if place_z is None else place_z
        out: List[dict] = []
        for a in actions:
            enriched = dict(a)
            enriched["from_xyz"] = self.coords.xyz(a["from_square"], pz)
            enriched["to_xyz"] = self.coords.xyz(a["to_square"], qz)
            out.append(enriched)
        return out
